// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gua_info.proto

#ifndef PROTOBUF_INCLUDED_gua_5finfo_2eproto
#define PROTOBUF_INCLUDED_gua_5finfo_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_gua_5finfo_2eproto 

namespace protobuf_gua_5finfo_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_gua_5finfo_2eproto
class dao_de_jing;
class dao_de_jingDefaultTypeInternal;
extern dao_de_jingDefaultTypeInternal _dao_de_jing_default_instance_;
class gua;
class guaDefaultTypeInternal;
extern guaDefaultTypeInternal _gua_default_instance_;
class yao;
class yaoDefaultTypeInternal;
extern yaoDefaultTypeInternal _yao_default_instance_;
namespace google {
namespace protobuf {
template<> ::dao_de_jing* Arena::CreateMaybeMessage<::dao_de_jing>(Arena*);
template<> ::gua* Arena::CreateMaybeMessage<::gua>(Arena*);
template<> ::yao* Arena::CreateMaybeMessage<::yao>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class yao : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:yao) */ {
 public:
  yao();
  virtual ~yao();

  yao(const yao& from);

  inline yao& operator=(const yao& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  yao(yao&& from) noexcept
    : yao() {
    *this = ::std::move(from);
  }

  inline yao& operator=(yao&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const yao& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const yao* internal_default_instance() {
    return reinterpret_cast<const yao*>(
               &_yao_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(yao* other);
  friend void swap(yao& a, yao& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline yao* New() const final {
    return CreateMaybeMessage<yao>(NULL);
  }

  yao* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<yao>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const yao& from);
  void MergeFrom(const yao& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(yao* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes info = 2;
  void clear_info();
  static const int kInfoFieldNumber = 2;
  const ::std::string& info() const;
  void set_info(const ::std::string& value);
  #if LANG_CXX11
  void set_info(::std::string&& value);
  #endif
  void set_info(const char* value);
  void set_info(const void* value, size_t size);
  ::std::string* mutable_info();
  ::std::string* release_info();
  void set_allocated_info(::std::string* info);

  // bool is_yang = 1;
  void clear_is_yang();
  static const int kIsYangFieldNumber = 1;
  bool is_yang() const;
  void set_is_yang(bool value);

  // @@protoc_insertion_point(class_scope:yao)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr info_;
  bool is_yang_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_gua_5finfo_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class gua : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gua) */ {
 public:
  gua();
  virtual ~gua();

  gua(const gua& from);

  inline gua& operator=(const gua& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  gua(gua&& from) noexcept
    : gua() {
    *this = ::std::move(from);
  }

  inline gua& operator=(gua&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const gua& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const gua* internal_default_instance() {
    return reinterpret_cast<const gua*>(
               &_gua_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(gua* other);
  friend void swap(gua& a, gua& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline gua* New() const final {
    return CreateMaybeMessage<gua>(NULL);
  }

  gua* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<gua>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const gua& from);
  void MergeFrom(const gua& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(gua* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .yao ben_gua_yao_info = 3;
  int ben_gua_yao_info_size() const;
  void clear_ben_gua_yao_info();
  static const int kBenGuaYaoInfoFieldNumber = 3;
  ::yao* mutable_ben_gua_yao_info(int index);
  ::google::protobuf::RepeatedPtrField< ::yao >*
      mutable_ben_gua_yao_info();
  const ::yao& ben_gua_yao_info(int index) const;
  ::yao* add_ben_gua_yao_info();
  const ::google::protobuf::RepeatedPtrField< ::yao >&
      ben_gua_yao_info() const;

  // repeated .yao bian_gua_yao_info = 6;
  int bian_gua_yao_info_size() const;
  void clear_bian_gua_yao_info();
  static const int kBianGuaYaoInfoFieldNumber = 6;
  ::yao* mutable_bian_gua_yao_info(int index);
  ::google::protobuf::RepeatedPtrField< ::yao >*
      mutable_bian_gua_yao_info();
  const ::yao& bian_gua_yao_info(int index) const;
  ::yao* add_bian_gua_yao_info();
  const ::google::protobuf::RepeatedPtrField< ::yao >&
      bian_gua_yao_info() const;

  // bytes ben_gua_name = 1;
  void clear_ben_gua_name();
  static const int kBenGuaNameFieldNumber = 1;
  const ::std::string& ben_gua_name() const;
  void set_ben_gua_name(const ::std::string& value);
  #if LANG_CXX11
  void set_ben_gua_name(::std::string&& value);
  #endif
  void set_ben_gua_name(const char* value);
  void set_ben_gua_name(const void* value, size_t size);
  ::std::string* mutable_ben_gua_name();
  ::std::string* release_ben_gua_name();
  void set_allocated_ben_gua_name(::std::string* ben_gua_name);

  // bytes ben_gua_info = 2;
  void clear_ben_gua_info();
  static const int kBenGuaInfoFieldNumber = 2;
  const ::std::string& ben_gua_info() const;
  void set_ben_gua_info(const ::std::string& value);
  #if LANG_CXX11
  void set_ben_gua_info(::std::string&& value);
  #endif
  void set_ben_gua_info(const char* value);
  void set_ben_gua_info(const void* value, size_t size);
  ::std::string* mutable_ben_gua_info();
  ::std::string* release_ben_gua_info();
  void set_allocated_ben_gua_info(::std::string* ben_gua_info);

  // bytes bian_gua_name = 4;
  void clear_bian_gua_name();
  static const int kBianGuaNameFieldNumber = 4;
  const ::std::string& bian_gua_name() const;
  void set_bian_gua_name(const ::std::string& value);
  #if LANG_CXX11
  void set_bian_gua_name(::std::string&& value);
  #endif
  void set_bian_gua_name(const char* value);
  void set_bian_gua_name(const void* value, size_t size);
  ::std::string* mutable_bian_gua_name();
  ::std::string* release_bian_gua_name();
  void set_allocated_bian_gua_name(::std::string* bian_gua_name);

  // bytes bian_gua_info = 5;
  void clear_bian_gua_info();
  static const int kBianGuaInfoFieldNumber = 5;
  const ::std::string& bian_gua_info() const;
  void set_bian_gua_info(const ::std::string& value);
  #if LANG_CXX11
  void set_bian_gua_info(::std::string&& value);
  #endif
  void set_bian_gua_info(const char* value);
  void set_bian_gua_info(const void* value, size_t size);
  ::std::string* mutable_bian_gua_info();
  ::std::string* release_bian_gua_info();
  void set_allocated_bian_gua_info(::std::string* bian_gua_info);

  // int32 bian_yao_count = 7;
  void clear_bian_yao_count();
  static const int kBianYaoCountFieldNumber = 7;
  ::google::protobuf::int32 bian_yao_count() const;
  void set_bian_yao_count(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:gua)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::yao > ben_gua_yao_info_;
  ::google::protobuf::RepeatedPtrField< ::yao > bian_gua_yao_info_;
  ::google::protobuf::internal::ArenaStringPtr ben_gua_name_;
  ::google::protobuf::internal::ArenaStringPtr ben_gua_info_;
  ::google::protobuf::internal::ArenaStringPtr bian_gua_name_;
  ::google::protobuf::internal::ArenaStringPtr bian_gua_info_;
  ::google::protobuf::int32 bian_yao_count_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_gua_5finfo_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class dao_de_jing : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dao_de_jing) */ {
 public:
  dao_de_jing();
  virtual ~dao_de_jing();

  dao_de_jing(const dao_de_jing& from);

  inline dao_de_jing& operator=(const dao_de_jing& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  dao_de_jing(dao_de_jing&& from) noexcept
    : dao_de_jing() {
    *this = ::std::move(from);
  }

  inline dao_de_jing& operator=(dao_de_jing&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const dao_de_jing& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const dao_de_jing* internal_default_instance() {
    return reinterpret_cast<const dao_de_jing*>(
               &_dao_de_jing_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(dao_de_jing* other);
  friend void swap(dao_de_jing& a, dao_de_jing& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline dao_de_jing* New() const final {
    return CreateMaybeMessage<dao_de_jing>(NULL);
  }

  dao_de_jing* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<dao_de_jing>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const dao_de_jing& from);
  void MergeFrom(const dao_de_jing& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(dao_de_jing* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes message = 1;
  void clear_message();
  static const int kMessageFieldNumber = 1;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const void* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:dao_de_jing)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_gua_5finfo_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// yao

// bool is_yang = 1;
inline void yao::clear_is_yang() {
  is_yang_ = false;
}
inline bool yao::is_yang() const {
  // @@protoc_insertion_point(field_get:yao.is_yang)
  return is_yang_;
}
inline void yao::set_is_yang(bool value) {
  
  is_yang_ = value;
  // @@protoc_insertion_point(field_set:yao.is_yang)
}

// bytes info = 2;
inline void yao::clear_info() {
  info_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& yao::info() const {
  // @@protoc_insertion_point(field_get:yao.info)
  return info_.GetNoArena();
}
inline void yao::set_info(const ::std::string& value) {
  
  info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:yao.info)
}
#if LANG_CXX11
inline void yao::set_info(::std::string&& value) {
  
  info_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:yao.info)
}
#endif
inline void yao::set_info(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yao.info)
}
inline void yao::set_info(const void* value, size_t size) {
  
  info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yao.info)
}
inline ::std::string* yao::mutable_info() {
  
  // @@protoc_insertion_point(field_mutable:yao.info)
  return info_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* yao::release_info() {
  // @@protoc_insertion_point(field_release:yao.info)
  
  return info_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void yao::set_allocated_info(::std::string* info) {
  if (info != NULL) {
    
  } else {
    
  }
  info_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), info);
  // @@protoc_insertion_point(field_set_allocated:yao.info)
}

// -------------------------------------------------------------------

// gua

// bytes ben_gua_name = 1;
inline void gua::clear_ben_gua_name() {
  ben_gua_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& gua::ben_gua_name() const {
  // @@protoc_insertion_point(field_get:gua.ben_gua_name)
  return ben_gua_name_.GetNoArena();
}
inline void gua::set_ben_gua_name(const ::std::string& value) {
  
  ben_gua_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gua.ben_gua_name)
}
#if LANG_CXX11
inline void gua::set_ben_gua_name(::std::string&& value) {
  
  ben_gua_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gua.ben_gua_name)
}
#endif
inline void gua::set_ben_gua_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  ben_gua_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gua.ben_gua_name)
}
inline void gua::set_ben_gua_name(const void* value, size_t size) {
  
  ben_gua_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gua.ben_gua_name)
}
inline ::std::string* gua::mutable_ben_gua_name() {
  
  // @@protoc_insertion_point(field_mutable:gua.ben_gua_name)
  return ben_gua_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* gua::release_ben_gua_name() {
  // @@protoc_insertion_point(field_release:gua.ben_gua_name)
  
  return ben_gua_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void gua::set_allocated_ben_gua_name(::std::string* ben_gua_name) {
  if (ben_gua_name != NULL) {
    
  } else {
    
  }
  ben_gua_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ben_gua_name);
  // @@protoc_insertion_point(field_set_allocated:gua.ben_gua_name)
}

// bytes ben_gua_info = 2;
inline void gua::clear_ben_gua_info() {
  ben_gua_info_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& gua::ben_gua_info() const {
  // @@protoc_insertion_point(field_get:gua.ben_gua_info)
  return ben_gua_info_.GetNoArena();
}
inline void gua::set_ben_gua_info(const ::std::string& value) {
  
  ben_gua_info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gua.ben_gua_info)
}
#if LANG_CXX11
inline void gua::set_ben_gua_info(::std::string&& value) {
  
  ben_gua_info_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gua.ben_gua_info)
}
#endif
inline void gua::set_ben_gua_info(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  ben_gua_info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gua.ben_gua_info)
}
inline void gua::set_ben_gua_info(const void* value, size_t size) {
  
  ben_gua_info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gua.ben_gua_info)
}
inline ::std::string* gua::mutable_ben_gua_info() {
  
  // @@protoc_insertion_point(field_mutable:gua.ben_gua_info)
  return ben_gua_info_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* gua::release_ben_gua_info() {
  // @@protoc_insertion_point(field_release:gua.ben_gua_info)
  
  return ben_gua_info_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void gua::set_allocated_ben_gua_info(::std::string* ben_gua_info) {
  if (ben_gua_info != NULL) {
    
  } else {
    
  }
  ben_gua_info_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ben_gua_info);
  // @@protoc_insertion_point(field_set_allocated:gua.ben_gua_info)
}

// repeated .yao ben_gua_yao_info = 3;
inline int gua::ben_gua_yao_info_size() const {
  return ben_gua_yao_info_.size();
}
inline void gua::clear_ben_gua_yao_info() {
  ben_gua_yao_info_.Clear();
}
inline ::yao* gua::mutable_ben_gua_yao_info(int index) {
  // @@protoc_insertion_point(field_mutable:gua.ben_gua_yao_info)
  return ben_gua_yao_info_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::yao >*
gua::mutable_ben_gua_yao_info() {
  // @@protoc_insertion_point(field_mutable_list:gua.ben_gua_yao_info)
  return &ben_gua_yao_info_;
}
inline const ::yao& gua::ben_gua_yao_info(int index) const {
  // @@protoc_insertion_point(field_get:gua.ben_gua_yao_info)
  return ben_gua_yao_info_.Get(index);
}
inline ::yao* gua::add_ben_gua_yao_info() {
  // @@protoc_insertion_point(field_add:gua.ben_gua_yao_info)
  return ben_gua_yao_info_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::yao >&
gua::ben_gua_yao_info() const {
  // @@protoc_insertion_point(field_list:gua.ben_gua_yao_info)
  return ben_gua_yao_info_;
}

// bytes bian_gua_name = 4;
inline void gua::clear_bian_gua_name() {
  bian_gua_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& gua::bian_gua_name() const {
  // @@protoc_insertion_point(field_get:gua.bian_gua_name)
  return bian_gua_name_.GetNoArena();
}
inline void gua::set_bian_gua_name(const ::std::string& value) {
  
  bian_gua_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gua.bian_gua_name)
}
#if LANG_CXX11
inline void gua::set_bian_gua_name(::std::string&& value) {
  
  bian_gua_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gua.bian_gua_name)
}
#endif
inline void gua::set_bian_gua_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  bian_gua_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gua.bian_gua_name)
}
inline void gua::set_bian_gua_name(const void* value, size_t size) {
  
  bian_gua_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gua.bian_gua_name)
}
inline ::std::string* gua::mutable_bian_gua_name() {
  
  // @@protoc_insertion_point(field_mutable:gua.bian_gua_name)
  return bian_gua_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* gua::release_bian_gua_name() {
  // @@protoc_insertion_point(field_release:gua.bian_gua_name)
  
  return bian_gua_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void gua::set_allocated_bian_gua_name(::std::string* bian_gua_name) {
  if (bian_gua_name != NULL) {
    
  } else {
    
  }
  bian_gua_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), bian_gua_name);
  // @@protoc_insertion_point(field_set_allocated:gua.bian_gua_name)
}

// bytes bian_gua_info = 5;
inline void gua::clear_bian_gua_info() {
  bian_gua_info_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& gua::bian_gua_info() const {
  // @@protoc_insertion_point(field_get:gua.bian_gua_info)
  return bian_gua_info_.GetNoArena();
}
inline void gua::set_bian_gua_info(const ::std::string& value) {
  
  bian_gua_info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gua.bian_gua_info)
}
#if LANG_CXX11
inline void gua::set_bian_gua_info(::std::string&& value) {
  
  bian_gua_info_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gua.bian_gua_info)
}
#endif
inline void gua::set_bian_gua_info(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  bian_gua_info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gua.bian_gua_info)
}
inline void gua::set_bian_gua_info(const void* value, size_t size) {
  
  bian_gua_info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gua.bian_gua_info)
}
inline ::std::string* gua::mutable_bian_gua_info() {
  
  // @@protoc_insertion_point(field_mutable:gua.bian_gua_info)
  return bian_gua_info_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* gua::release_bian_gua_info() {
  // @@protoc_insertion_point(field_release:gua.bian_gua_info)
  
  return bian_gua_info_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void gua::set_allocated_bian_gua_info(::std::string* bian_gua_info) {
  if (bian_gua_info != NULL) {
    
  } else {
    
  }
  bian_gua_info_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), bian_gua_info);
  // @@protoc_insertion_point(field_set_allocated:gua.bian_gua_info)
}

// repeated .yao bian_gua_yao_info = 6;
inline int gua::bian_gua_yao_info_size() const {
  return bian_gua_yao_info_.size();
}
inline void gua::clear_bian_gua_yao_info() {
  bian_gua_yao_info_.Clear();
}
inline ::yao* gua::mutable_bian_gua_yao_info(int index) {
  // @@protoc_insertion_point(field_mutable:gua.bian_gua_yao_info)
  return bian_gua_yao_info_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::yao >*
gua::mutable_bian_gua_yao_info() {
  // @@protoc_insertion_point(field_mutable_list:gua.bian_gua_yao_info)
  return &bian_gua_yao_info_;
}
inline const ::yao& gua::bian_gua_yao_info(int index) const {
  // @@protoc_insertion_point(field_get:gua.bian_gua_yao_info)
  return bian_gua_yao_info_.Get(index);
}
inline ::yao* gua::add_bian_gua_yao_info() {
  // @@protoc_insertion_point(field_add:gua.bian_gua_yao_info)
  return bian_gua_yao_info_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::yao >&
gua::bian_gua_yao_info() const {
  // @@protoc_insertion_point(field_list:gua.bian_gua_yao_info)
  return bian_gua_yao_info_;
}

// int32 bian_yao_count = 7;
inline void gua::clear_bian_yao_count() {
  bian_yao_count_ = 0;
}
inline ::google::protobuf::int32 gua::bian_yao_count() const {
  // @@protoc_insertion_point(field_get:gua.bian_yao_count)
  return bian_yao_count_;
}
inline void gua::set_bian_yao_count(::google::protobuf::int32 value) {
  
  bian_yao_count_ = value;
  // @@protoc_insertion_point(field_set:gua.bian_yao_count)
}

// -------------------------------------------------------------------

// dao_de_jing

// bytes message = 1;
inline void dao_de_jing::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& dao_de_jing::message() const {
  // @@protoc_insertion_point(field_get:dao_de_jing.message)
  return message_.GetNoArena();
}
inline void dao_de_jing::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dao_de_jing.message)
}
#if LANG_CXX11
inline void dao_de_jing::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:dao_de_jing.message)
}
#endif
inline void dao_de_jing::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dao_de_jing.message)
}
inline void dao_de_jing::set_message(const void* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dao_de_jing.message)
}
inline ::std::string* dao_de_jing::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:dao_de_jing.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* dao_de_jing::release_message() {
  // @@protoc_insertion_point(field_release:dao_de_jing.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void dao_de_jing::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:dao_de_jing.message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_gua_5finfo_2eproto
