// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gua_info.proto

#include "gua_info.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_gua_5finfo_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_gua_5finfo_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_yao;
}  // namespace protobuf_gua_5finfo_2eproto
class yaoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<yao>
      _instance;
} _yao_default_instance_;
class guaDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<gua>
      _instance;
} _gua_default_instance_;
class dao_de_jingDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<dao_de_jing>
      _instance;
} _dao_de_jing_default_instance_;
namespace protobuf_gua_5finfo_2eproto {
static void InitDefaultsyao() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_yao_default_instance_;
    new (ptr) ::yao();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::yao::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_yao =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsyao}, {}};

static void InitDefaultsgua() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_gua_default_instance_;
    new (ptr) ::gua();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::gua::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_gua =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsgua}, {
      &protobuf_gua_5finfo_2eproto::scc_info_yao.base,}};

static void InitDefaultsdao_de_jing() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_dao_de_jing_default_instance_;
    new (ptr) ::dao_de_jing();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::dao_de_jing::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_dao_de_jing =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsdao_de_jing}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_yao.base);
  ::google::protobuf::internal::InitSCC(&scc_info_gua.base);
  ::google::protobuf::internal::InitSCC(&scc_info_dao_de_jing.base);
}

::google::protobuf::Metadata file_level_metadata[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::yao, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::yao, is_yang_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::yao, info_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gua, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gua, ben_gua_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gua, ben_gua_info_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gua, ben_gua_yao_info_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gua, bian_gua_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gua, bian_gua_info_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gua, bian_gua_yao_info_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gua, bian_yao_count_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dao_de_jing, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dao_de_jing, message_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::yao)},
  { 7, -1, sizeof(::gua)},
  { 19, -1, sizeof(::dao_de_jing)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_yao_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_gua_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_dao_de_jing_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "gua_info.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\016gua_info.proto\"$\n\003yao\022\017\n\007is_yang\030\001 \001(\010"
      "\022\014\n\004info\030\002 \001(\014\"\270\001\n\003gua\022\024\n\014ben_gua_name\030\001"
      " \001(\014\022\024\n\014ben_gua_info\030\002 \001(\014\022\036\n\020ben_gua_ya"
      "o_info\030\003 \003(\0132\004.yao\022\025\n\rbian_gua_name\030\004 \001("
      "\014\022\025\n\rbian_gua_info\030\005 \001(\014\022\037\n\021bian_gua_yao"
      "_info\030\006 \003(\0132\004.yao\022\026\n\016bian_yao_count\030\007 \001("
      "\005\"\036\n\013dao_de_jing\022\017\n\007message\030\001 \001(\014b\006proto"
      "3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 281);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "gua_info.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_gua_5finfo_2eproto

// ===================================================================

void yao::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int yao::kIsYangFieldNumber;
const int yao::kInfoFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

yao::yao()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_gua_5finfo_2eproto::scc_info_yao.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:yao)
}
yao::yao(const yao& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  info_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.info().size() > 0) {
    info_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.info_);
  }
  is_yang_ = from.is_yang_;
  // @@protoc_insertion_point(copy_constructor:yao)
}

void yao::SharedCtor() {
  info_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  is_yang_ = false;
}

yao::~yao() {
  // @@protoc_insertion_point(destructor:yao)
  SharedDtor();
}

void yao::SharedDtor() {
  info_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void yao::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* yao::descriptor() {
  ::protobuf_gua_5finfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_gua_5finfo_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const yao& yao::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_gua_5finfo_2eproto::scc_info_yao.base);
  return *internal_default_instance();
}


void yao::Clear() {
// @@protoc_insertion_point(message_clear_start:yao)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  info_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  is_yang_ = false;
  _internal_metadata_.Clear();
}

bool yao::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:yao)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool is_yang = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &is_yang_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes info = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_info()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:yao)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:yao)
  return false;
#undef DO_
}

void yao::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:yao)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool is_yang = 1;
  if (this->is_yang() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->is_yang(), output);
  }

  // bytes info = 2;
  if (this->info().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->info(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:yao)
}

::google::protobuf::uint8* yao::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:yao)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool is_yang = 1;
  if (this->is_yang() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->is_yang(), target);
  }

  // bytes info = 2;
  if (this->info().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->info(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yao)
  return target;
}

size_t yao::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yao)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes info = 2;
  if (this->info().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->info());
  }

  // bool is_yang = 1;
  if (this->is_yang() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void yao::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:yao)
  GOOGLE_DCHECK_NE(&from, this);
  const yao* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const yao>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:yao)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:yao)
    MergeFrom(*source);
  }
}

void yao::MergeFrom(const yao& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yao)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.info().size() > 0) {

    info_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.info_);
  }
  if (from.is_yang() != 0) {
    set_is_yang(from.is_yang());
  }
}

void yao::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:yao)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void yao::CopyFrom(const yao& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yao)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool yao::IsInitialized() const {
  return true;
}

void yao::Swap(yao* other) {
  if (other == this) return;
  InternalSwap(other);
}
void yao::InternalSwap(yao* other) {
  using std::swap;
  info_.Swap(&other->info_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(is_yang_, other->is_yang_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata yao::GetMetadata() const {
  protobuf_gua_5finfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_gua_5finfo_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void gua::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int gua::kBenGuaNameFieldNumber;
const int gua::kBenGuaInfoFieldNumber;
const int gua::kBenGuaYaoInfoFieldNumber;
const int gua::kBianGuaNameFieldNumber;
const int gua::kBianGuaInfoFieldNumber;
const int gua::kBianGuaYaoInfoFieldNumber;
const int gua::kBianYaoCountFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

gua::gua()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_gua_5finfo_2eproto::scc_info_gua.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:gua)
}
gua::gua(const gua& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      ben_gua_yao_info_(from.ben_gua_yao_info_),
      bian_gua_yao_info_(from.bian_gua_yao_info_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ben_gua_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.ben_gua_name().size() > 0) {
    ben_gua_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ben_gua_name_);
  }
  ben_gua_info_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.ben_gua_info().size() > 0) {
    ben_gua_info_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ben_gua_info_);
  }
  bian_gua_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.bian_gua_name().size() > 0) {
    bian_gua_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bian_gua_name_);
  }
  bian_gua_info_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.bian_gua_info().size() > 0) {
    bian_gua_info_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bian_gua_info_);
  }
  bian_yao_count_ = from.bian_yao_count_;
  // @@protoc_insertion_point(copy_constructor:gua)
}

void gua::SharedCtor() {
  ben_gua_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ben_gua_info_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bian_gua_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bian_gua_info_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bian_yao_count_ = 0;
}

gua::~gua() {
  // @@protoc_insertion_point(destructor:gua)
  SharedDtor();
}

void gua::SharedDtor() {
  ben_gua_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ben_gua_info_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bian_gua_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bian_gua_info_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void gua::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* gua::descriptor() {
  ::protobuf_gua_5finfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_gua_5finfo_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const gua& gua::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_gua_5finfo_2eproto::scc_info_gua.base);
  return *internal_default_instance();
}


void gua::Clear() {
// @@protoc_insertion_point(message_clear_start:gua)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ben_gua_yao_info_.Clear();
  bian_gua_yao_info_.Clear();
  ben_gua_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ben_gua_info_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bian_gua_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bian_gua_info_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bian_yao_count_ = 0;
  _internal_metadata_.Clear();
}

bool gua::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:gua)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes ben_gua_name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_ben_gua_name()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes ben_gua_info = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_ben_gua_info()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .yao ben_gua_yao_info = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_ben_gua_yao_info()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes bian_gua_name = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_bian_gua_name()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes bian_gua_info = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_bian_gua_info()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .yao bian_gua_yao_info = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_bian_gua_yao_info()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 bian_yao_count = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &bian_yao_count_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:gua)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:gua)
  return false;
#undef DO_
}

void gua::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:gua)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes ben_gua_name = 1;
  if (this->ben_gua_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->ben_gua_name(), output);
  }

  // bytes ben_gua_info = 2;
  if (this->ben_gua_info().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->ben_gua_info(), output);
  }

  // repeated .yao ben_gua_yao_info = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->ben_gua_yao_info_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3,
      this->ben_gua_yao_info(static_cast<int>(i)),
      output);
  }

  // bytes bian_gua_name = 4;
  if (this->bian_gua_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      4, this->bian_gua_name(), output);
  }

  // bytes bian_gua_info = 5;
  if (this->bian_gua_info().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      5, this->bian_gua_info(), output);
  }

  // repeated .yao bian_gua_yao_info = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->bian_gua_yao_info_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6,
      this->bian_gua_yao_info(static_cast<int>(i)),
      output);
  }

  // int32 bian_yao_count = 7;
  if (this->bian_yao_count() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->bian_yao_count(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:gua)
}

::google::protobuf::uint8* gua::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:gua)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes ben_gua_name = 1;
  if (this->ben_gua_name().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->ben_gua_name(), target);
  }

  // bytes ben_gua_info = 2;
  if (this->ben_gua_info().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->ben_gua_info(), target);
  }

  // repeated .yao ben_gua_yao_info = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->ben_gua_yao_info_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->ben_gua_yao_info(static_cast<int>(i)), deterministic, target);
  }

  // bytes bian_gua_name = 4;
  if (this->bian_gua_name().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        4, this->bian_gua_name(), target);
  }

  // bytes bian_gua_info = 5;
  if (this->bian_gua_info().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        5, this->bian_gua_info(), target);
  }

  // repeated .yao bian_gua_yao_info = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->bian_gua_yao_info_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        6, this->bian_gua_yao_info(static_cast<int>(i)), deterministic, target);
  }

  // int32 bian_yao_count = 7;
  if (this->bian_yao_count() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(7, this->bian_yao_count(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gua)
  return target;
}

size_t gua::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gua)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .yao ben_gua_yao_info = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->ben_gua_yao_info_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->ben_gua_yao_info(static_cast<int>(i)));
    }
  }

  // repeated .yao bian_gua_yao_info = 6;
  {
    unsigned int count = static_cast<unsigned int>(this->bian_gua_yao_info_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->bian_gua_yao_info(static_cast<int>(i)));
    }
  }

  // bytes ben_gua_name = 1;
  if (this->ben_gua_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->ben_gua_name());
  }

  // bytes ben_gua_info = 2;
  if (this->ben_gua_info().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->ben_gua_info());
  }

  // bytes bian_gua_name = 4;
  if (this->bian_gua_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->bian_gua_name());
  }

  // bytes bian_gua_info = 5;
  if (this->bian_gua_info().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->bian_gua_info());
  }

  // int32 bian_yao_count = 7;
  if (this->bian_yao_count() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->bian_yao_count());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void gua::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:gua)
  GOOGLE_DCHECK_NE(&from, this);
  const gua* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const gua>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:gua)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:gua)
    MergeFrom(*source);
  }
}

void gua::MergeFrom(const gua& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:gua)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  ben_gua_yao_info_.MergeFrom(from.ben_gua_yao_info_);
  bian_gua_yao_info_.MergeFrom(from.bian_gua_yao_info_);
  if (from.ben_gua_name().size() > 0) {

    ben_gua_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ben_gua_name_);
  }
  if (from.ben_gua_info().size() > 0) {

    ben_gua_info_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ben_gua_info_);
  }
  if (from.bian_gua_name().size() > 0) {

    bian_gua_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bian_gua_name_);
  }
  if (from.bian_gua_info().size() > 0) {

    bian_gua_info_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bian_gua_info_);
  }
  if (from.bian_yao_count() != 0) {
    set_bian_yao_count(from.bian_yao_count());
  }
}

void gua::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:gua)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void gua::CopyFrom(const gua& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gua)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool gua::IsInitialized() const {
  return true;
}

void gua::Swap(gua* other) {
  if (other == this) return;
  InternalSwap(other);
}
void gua::InternalSwap(gua* other) {
  using std::swap;
  CastToBase(&ben_gua_yao_info_)->InternalSwap(CastToBase(&other->ben_gua_yao_info_));
  CastToBase(&bian_gua_yao_info_)->InternalSwap(CastToBase(&other->bian_gua_yao_info_));
  ben_gua_name_.Swap(&other->ben_gua_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  ben_gua_info_.Swap(&other->ben_gua_info_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  bian_gua_name_.Swap(&other->bian_gua_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  bian_gua_info_.Swap(&other->bian_gua_info_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(bian_yao_count_, other->bian_yao_count_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata gua::GetMetadata() const {
  protobuf_gua_5finfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_gua_5finfo_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void dao_de_jing::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int dao_de_jing::kMessageFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

dao_de_jing::dao_de_jing()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_gua_5finfo_2eproto::scc_info_dao_de_jing.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:dao_de_jing)
}
dao_de_jing::dao_de_jing(const dao_de_jing& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.message().size() > 0) {
    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  // @@protoc_insertion_point(copy_constructor:dao_de_jing)
}

void dao_de_jing::SharedCtor() {
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

dao_de_jing::~dao_de_jing() {
  // @@protoc_insertion_point(destructor:dao_de_jing)
  SharedDtor();
}

void dao_de_jing::SharedDtor() {
  message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void dao_de_jing::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* dao_de_jing::descriptor() {
  ::protobuf_gua_5finfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_gua_5finfo_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const dao_de_jing& dao_de_jing::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_gua_5finfo_2eproto::scc_info_dao_de_jing.base);
  return *internal_default_instance();
}


void dao_de_jing::Clear() {
// @@protoc_insertion_point(message_clear_start:dao_de_jing)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool dao_de_jing::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dao_de_jing)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes message = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_message()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dao_de_jing)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dao_de_jing)
  return false;
#undef DO_
}

void dao_de_jing::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dao_de_jing)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes message = 1;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->message(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:dao_de_jing)
}

::google::protobuf::uint8* dao_de_jing::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:dao_de_jing)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes message = 1;
  if (this->message().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->message(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dao_de_jing)
  return target;
}

size_t dao_de_jing::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dao_de_jing)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes message = 1;
  if (this->message().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->message());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void dao_de_jing::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:dao_de_jing)
  GOOGLE_DCHECK_NE(&from, this);
  const dao_de_jing* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const dao_de_jing>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:dao_de_jing)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:dao_de_jing)
    MergeFrom(*source);
  }
}

void dao_de_jing::MergeFrom(const dao_de_jing& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:dao_de_jing)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.message().size() > 0) {

    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
}

void dao_de_jing::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:dao_de_jing)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void dao_de_jing::CopyFrom(const dao_de_jing& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dao_de_jing)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool dao_de_jing::IsInitialized() const {
  return true;
}

void dao_de_jing::Swap(dao_de_jing* other) {
  if (other == this) return;
  InternalSwap(other);
}
void dao_de_jing::InternalSwap(dao_de_jing* other) {
  using std::swap;
  message_.Swap(&other->message_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata dao_de_jing::GetMetadata() const {
  protobuf_gua_5finfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_gua_5finfo_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::yao* Arena::CreateMaybeMessage< ::yao >(Arena* arena) {
  return Arena::CreateInternal< ::yao >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::gua* Arena::CreateMaybeMessage< ::gua >(Arena* arena) {
  return Arena::CreateInternal< ::gua >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::dao_de_jing* Arena::CreateMaybeMessage< ::dao_de_jing >(Arena* arena) {
  return Arena::CreateInternal< ::dao_de_jing >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
